### ISSUE TITLE
Misspelled

### ISSUE THREAD

**Issue by neuhaus** [NOLOVR/NOLO-Windows-SDK#1]
The spelling of the function "disConnenct_FunCallBack" should be corrected.

I suppose the correct spelling is "disConnect_FunCallBack"

**Comment by LoSealL** [comment]
Also found in struct `HMD` `HMDInirPostion` should be `HMDInitPostion`

**Comment by LyrobotixNolo** [comment]
@LoSealL @neuhaus ,hi,Thank you very much for discovering that I will correct it immediately

**Comment by neuhaus** [comment]
HMDInirPostion should be HMDInitPosition

**Comment by neuhaus** [comment]
You missed one typo in an example where it still says `HMDInirPostion` at
https://github.com/NOLOVR/NOLO-Windows-SDK/blob/b80683e2e284e5e43953e99dc39aa9fdd8ac3470/Examples/NOLO_ZEROMQ_SDK_Examples/nolo_driver_sourceCode/NOLO_Utility.h#L193

**Comment by LyuzhouZ** [comment]
Thanks! We'll fix that in the next version.
