### ISSUE TITLE
Errors in nolo_api.h (USB-HID SDK)

### ISSUE THREAD

**Issue by TheDeveloperGuy** [NOLOVR/NOLO-Windows-SDK#10]
On line 66:

long rhs_const_copy(rhs);

should be:

float rhs_const_copy(rhs);

On line 421:

NOLO_API EBattery _cdecl set_Nolo_TurnAroundKey(EDoubleClickKeyType keyType);

should be:

NOLO_API void _cdecl set_Nolo_TurnAroundKey(EDoubleClickKeyType keyType);

**Comment by GXiaoyang** [comment]
@TheDeveloperGuy 
hi
thank you very much
