### ISSUE TITLE
How to do "ceiling mode" with USB-HID SDK?

### ISSUE THREAD

**Issue by TheDeveloperGuy** [NOLOVR/NOLO-Windows-SDK#11]
@GXiaoyang @Hettylool  Is there some code you can show me for how "ceiling mode" is done in the zeroMQ SDK? I know there are two different DLLs for "normal" and "ceiling" mode. I would like some way to switch the USB-HID SDK into "ceiling mode" eg. 

NOLO_API  void _cdecl set_Nolo_CeilingMode(bool enable);

If there's some code I can put in my driver to achieve the same thing, then maybe that isn't necessary. What is the difference between the "ceiling" mode DLL and the "normal" mode DLL?

**Comment by GXiaoyang** [comment]
@TheDeveloperGuy 
"ceiling mode" is not our first choice when it comes to our 360° programs, so we do not want to design this plan into our software, but we will provide "ceiling mode".

**Comment by TheDeveloperGuy** [comment]
@GXiaoyang  I don't think "ceiling mode" is a good idea, but a lot of users like it so what can we do? What does the Nolo driver do to make "ceiling mode"? Maybe it is better to do that in the SteamVR software?

**Comment by GXiaoyang** [comment]
@TheDeveloperGuy 
good afternoon
Now we provide simulation values, and the real value that provided by the hardware is being tested. I will finish testing as soon as possible, but we need to reserve the interface for it, we will not always provide the simulation value. No worries.

**Comment by GXiaoyang** [comment]
@TheDeveloperGuy 
For the 360-degree program, I will now provide 360-degree dll plug-in, and do not want to join the software, because do not want users to think that NOLO 360 degrees is "ceiling mode"

**Comment by TheDeveloperGuy** [comment]
@GXiaoyang  Thank you :)
