### ISSUE TITLE
Will there be an iOS SDK?

### ISSUE THREAD

**Issue by TheDeveloperGuy** [NOLOVR/NOLO-Windows-SDK#12]
@GXiaoyang @Hettylool Is there any plan to release an iOS SDK that lets you connect the NoloVR directly to the iPhone? It would be useful to have a completely wireless solution for iPhone (like there is for Android).

**Comment by LyuzhouZ** [comment]
We're currently focusing on PCs and Android phones. We may add support for iOS in the future but it could be a while before we make it.
