### ISSUE TITLE
Missing 32 bit version

### ISSUE THREAD

**Issue by TheDeveloperGuy** [NOLOVR/NOLO-Windows-SDK#15]
Latest update is missing 32 bit build. Needs to be there for a SteamVR driver release.

**Comment by TheDeveloperGuy** [comment]
A week later. No response. PLEASE FIX.

**Comment by TheDeveloperGuy** [comment]
@GXiaoyang @Hettylool @ZhangJN016 ^^^

**Comment by Hettylool** [comment]
@TheDeveloperGuy  will update soon

**Comment by Hettylool** [comment]
@TheDeveloperGuy  new version sdk will update on December 6th

**Comment by TheDeveloperGuy** [comment]
@Hettylool Waiting until 6th December is not acceptable.

**Comment by LyuzhouZ** [comment]
32-bit build is provided [here](https://github.com/NOLOVR/NOLO-Windows-SDK/tree/master/NOLOVR/NOLO_USBHID_SDK/bin)
