### ISSUE TITLE
Callback functions

### ISSUE THREAD

**Issue by TheDeveloperGuy** [NOLOVR/NOLO-Windows-SDK#2]
A big design problem with the SDK is how callbacks are done (in general). The standard way that callbacks are done in modern software is to use the following pattern:

`typedef void(*callbackFn)(void* context);`

`void registerCallback(callbackFn callback, void *context);`

This allows the code being called back to provide a pointer (for example to a C++ object) so that there isn't a need for global variables (which are generally a *very bad* idea in modern code). 

Here is what you would need to change:

`    typedef void(__cdecl *noloData_FuncCallBackNotify)(NoloData _noloData, void* context);`
`    typedef void(__cdecl *expandMsg_FuncCallBack)(ExpandMsgType expandMsgType, void* context);`
`    typedef void(__cdecl *funcCallBack)(void* context);`

However, as you probably don't want to break source/binary compatibility with existing apps/drivers, you will need to add these to your SDK:

`    typedef void(__cdecl *noloData_FuncCallBackNotifyEx)(NoloData _noloData, void* context);`
`    typedef void(__cdecl *expandMsg_FuncCallBackEx)(ExpandMsgType expandMsgType, void* context);`
`    typedef void(__cdecl *funcCallBackEx)(void* context);`

`    NOLO_API  bool _cdecl disConnect_FunCallBackEx(funcCallBackEx fun, void* context);`
`    NOLO_API  bool _cdecl connectSuccess_FunCallBackEx(funcCallBackEx fun, void* context);`

`    NOLO_API  bool _cdecl expandDataNotify_FuncCallBackEx(expandMsg_FuncCallBackEx fun, void* context);`
`    NOLO_API  bool _cdecl noloDataNotify_FuncCallBackEx(noloData_FuncCallBackNotifyEx fun, void* context);`

The context (which can be NULL) passed to the callback would be the context passed to the function that registers the callback eg.

    class Object
    {
    private:
        bool _connected;

        static void connectCallback(void *context)
        {
            Object *that = reinterpret_cast<Object*>(context);
            that->_connected = true;
        }

    public:
        Object::Object()
        {
            _connected = false;
            connectSuccess_FunCallBackEx(connectCallback, this);
        }
    };

**Comment by GXiaoyang** [comment]
Thank you for your help, I will try to do,and Also sorry for the current situation

**Comment by GXiaoyang** [comment]
@TheDeveloperGuy 
hi
Thank you very much

**Comment by GXiaoyang** [comment]
@TheDeveloperGuy 

Hope you can continue to help us，thank you

**Comment by TheDeveloperGuy** [comment]
@GXiaoyang Thank you for your quick response! No problem, this is pre-release, together we make it better... :)

**Comment by GXiaoyang** [comment]
@TheDeveloperGuy 
Thank you for your trust,this is my Shype :18770919510,miss you

**Comment by GXiaoyang** [comment]
@TheDeveloperGuy 

If you have a better suggestion, I will consider trying to do it

**Comment by TheDeveloperGuy** [comment]
@GXiaoyang It seems the best way forward is to add the "Ex" functions and callbacks. This way existing apps and drivers don't need to be changed.

**Comment by TheDeveloperGuy** [comment]
@GXiaoyang Very nice! 👍 

Corrected in the USB-HID SDK, which is the recommended SDK to use for SteamVR.
