### ISSUE TITLE
Add path to Nolo runtime

### ISSUE THREAD

**Issue by TheDeveloperGuy** [NOLOVR/NOLO-Windows-SDK#3]
Another issue with the SDK is that it isn't easy to remove link-time dependencies on the SDK. For instance, I won't make a special driver version for NoloVR, but instead, at run-time I will check for the presence of NoloVR libraries and load them if they're present. I don't want to ship Nolo libraries with my product (as most users won't have NoloVR), nor use hard-coded paths to the libraries.

So, (easiest) the Nolo installer writes a value to the registry containing the path to the NoloVR DLLs. The driver/app queries the registry, finds the path of the driver and then loads it. Afterwards it can do detection checks to determine if Nolo hardware is actually attached.

In any case, this will be better for you, as you really only want 1 copy of a Nolo DLL on the system (the copy the user installed with the driver). You don't want to be in the situation where you have each app having a different version of the Nolo DLL, none of which match the version installed with the (latest version of) the driver.

**Comment by GXiaoyang** [comment]
Thank you for your reminder, we will try to do it

**Comment by TheDeveloperGuy** [comment]
@GXiaoyang It should be simple to add the installation path to the registry during installation. The path to the DLL files can be determined from that path.

**Comment by TheDeveloperGuy** [comment]
Not an issue in the USB-HID SDK, which is the recommended SDK to use for SteamVR.
