### ISSUE TITLE
Missing noloDataNotify_FuncCallBack() export

### ISSUE THREAD

**Issue by TheDeveloperGuy** [NOLOVR/NOLO-Windows-SDK#4]
It does not (in the current 0.7 version) export the noloDataNotify_FuncCallBack(), although it does export expandDataNotify_FuncCallBack(). 

I cannot use the SDK without this function, and so I cannot proceed.

**Comment by GXiaoyang** [comment]
I thank you for discovering and sorry for my mistakes now that I have re-updated github and you can try again

**Comment by GXiaoyang** [comment]
@TheDeveloperGuy 
thank you very much

**Comment by TheDeveloperGuy** [comment]
@GXiaoyang Thanks!

**Comment by TheDeveloperGuy** [comment]
@GXiaoyang I can confirm this works well. Much smoother than polling! 😃
