### ISSUE TITLE
Strange rotation values

### ISSUE THREAD

**Issue by TheDeveloperGuy** [NOLOVR/NOLO-Windows-SDK#5]
So, I'm busy integrating NoloVR into my SteamVR driver and I've come up with some strangeness:

When I use the rotation quaternion supplied by the Nolo runtime I have to do a bit of manipulation to it before I can use it as a rotation quaternion for SteamVR.

To make it easier to understand and experiment with I convert the quaternion to euler (roll, yaw & pitch), then I perform the following:

        roll = M_PI_2 - roll;
        yaw = M_PI - yaw;
        pitch = M_PI - pitch;

before converting it back to quaternion and passing it to SteamVR. If I don't do this, up is down, left is right and tilt is fine. Why this is? This is using the values supplied by 0.60 and 0.70 drivers.

**Comment by GXiaoyang** [comment]
First of all, I am very grateful to you to use NOLO, which is part of the code I sent into the handle data to steamVR

	//data
	m_Pose.vecPosition[0] = data.pos[0];
	m_Pose.vecPosition[1] = data.pos[1];
	m_Pose.vecPosition[2] = -data.pos[2];
	m_Pose.qRotation.w = -data.rot_quat[0];// NOLO w
	m_Pose.qRotation.x = data.rot_quat[1];//NOLO x
	m_Pose.qRotation.y = data.rot_quat[2];//NOLO y
	m_Pose.qRotation.z = -data.rot_quat[3];// NOLO z


Hope to help you

**Comment by TheDeveloperGuy** [comment]
@GXiaoyang Thanks, that kind of works. I was already doing the z position correctly. If I use your method, the rotation axes are correct, but then the position data is incorrect (if I lean forward the view moves sideways). You can see the effect of this in the demo application supplied with the driver.

If I use my conversion then everything works correctly. I'm happy to keep using my conversion if this is expected behaviour from the SDK and is not likely to change.

**Comment by GXiaoyang** [comment]
@TheDeveloperGuy 
ok

**Comment by TheDeveloperGuy** [comment]
@GXiaoyang It looks as if the value given is from the point of view of the base station, looking at the HMD. If I change my conversion so that the roll is only reversed by 180 degrees (M_PI) then I get the same effect as your conversion.

**Comment by TheDeveloperGuy** [comment]
Strange values from the controllers as well. I need to do the same conversion on the controller rotation as well to get it to work correctly. On the controllers however the Z value of the position doesn't need to be reversed.

**Comment by TheDeveloperGuy** [comment]
@GXiaoyang There's definitely something funny going on here. Sometimes I must adjust the roll value by 2*PI, other times I must adjust it by PI. I've even had the situation where 1 controller needed to be adjusted by PI and the other 2*PI. 

Obviously there's something going wrong in the runtime, but I haven't found a way to reproduce the issue yet. If I shut down the Nolo app, unplug and switch everything off, then plug it in and switch it on before starting the Nolo app again it goes back to "normal", where everything must have its roll value adjusted by 2*PI.

I'm not happy to ship a version of my driver (which is now complete apart from this) without this issue resolved, as it will cause support issues for me.

**Comment by Hettylool** [comment]
@TheDeveloperGuy 
Thank you for your advise.and my colleague recently on business.
we will feedback asap.

**Comment by TheDeveloperGuy** [comment]
I'm beginning to think it may be an issue with where the base station is placed. If it is generally above where the HMD is (I had it on top of my monitor) then the runtime appears to put the tracking in "ceiling" mode. If it is on the desk (ie. generally below where the HMD is) then it seems to work OK (so far).

If this is the case, then the runtime should not make any decisions based on what it thinks is going on and rather let the user set this in the Nolo app.
