### ISSUE TITLE
Bug in recenter (double-clicking system) action

### ISSUE THREAD

**Issue by TheDeveloperGuy** [NOLOVR/NOLO-Windows-SDK#8]
It looks like double-clicking the power button may be intended to recenter the tracking. Before recentering, my driver must perform a transform of M_PI_2 on the roll angle of the quaternions provided for the HMD and controllers. After double-clicking the system button, I must change the transform to M_PI or the orientation reported by Nolo is incorrect (see https://github.com/NOLOVR/NOLO-Windows-SDK/issues/5 ).

Once this action has been performed, the hardware must be shut down and switched on again before the orientation reverts to the M_PI_2 state. Unfortunately there is no way for the driver/app to figure out it must do this if it starts when the Nolo runtime is already in this state (it can detect the double-click of the system button while it is running).

**Comment by TheDeveloperGuy** [comment]
It's necessary to double-click the system button on both controllers or one controller will need M_PI_2 transform and the other M_PI transform, which is obviously very confusing for the user.

**Comment by GXiaoyang** [comment]
@TheDeveloperGuy 
hi，
i  want to use Ivery software to run NOLO,
Where should I download? As well as the use of tutorials can provide some.
thank you very much

**Comment by TheDeveloperGuy** [comment]
@GXiaoyang It's not available yet, as I'm waiting for this bug to be fixed before I release anything. I'm not willing to release software with known bugs in it (even if those bugs are not mine and there is nothing I can do to work around them).

**Comment by GXiaoyang** [comment]
@TheDeveloperGuy 

I know what you mean, I know that when you double-click the power button, the handle yaw axis is 0, and you only need to set the yaw axis to 0 when you double-click the power button.

**Comment by GXiaoyang** [comment]
@TheDeveloperGuy 
hi
When you choose to use the helmet attitude data we provide, you do not have to deal with it

**Comment by GXiaoyang** [comment]
@TheDeveloperGuy 

Can i see the effect now? So better understand your thoughts

**Comment by GXiaoyang** [comment]
@TheDeveloperGuy 

Can i add your skype account? In order to better promote the work

**Comment by TheDeveloperGuy** [comment]
@GXiaoyang You can easily repeat this issue with the Nolo Visualiser software:

- Exit Nolo software
- Unplug HMD tracker
- Turn on base station, plug in HMD tracker, turn on controllers
- Start Nolo software
- Run Nolo visualiser
- Do not press any controller buttons and wait for a few seconds
- Move HMD around, you will see that the center is offset 90 degrees to left and that moving forwards moves the view sidewards etc. Let's call this state #A
- Double-click 'recenter' button
- Move HMD around, everything works OK. Let's call this state #B
- Exit Nolo visualiser
- Run Nolo visualiser
- Everything works OK without pressing any controller buttons (ie. state #B)

This is the issue that I am talking about. Any software/driver using the Nolo API cannot tell whether the state is #A or #B. It's not possible for the software/driver to change the state from #A to #B (this can only be done by the user double-clicking 'recenter), and it's not possible to change the state from #B to #A without shutting down Nolo software and unplugging headset tracker. 

I need to have a way to determine if Nolo is in state #A or #B, or I need it to always be in state #B, which is where your quaternion method (-w & -z) works correctly.

**Comment by TheDeveloperGuy** [comment]
@GXiaoyang Here you can also see the issues with the controllers. Sometimes they need to be 'recentered', sometimes they don't. Sometimes they will correct themselves, sometimes they won't. Sometimes one controller will be correct and the other one not. 

I hope you can understand that these Nolo bugs are not acceptable user experience for my software, even if other software authors are prepared to accept them. It's the philosophical aspect of 'quality'. The 'quality' is as high as the 'quality' of the weakest component.

**Comment by GXiaoyang** [comment]
@TheDeveloperGuy 

As long as the user into the game we will prompt the user first double-click the power button, calibration positioning.

**Comment by GXiaoyang** [comment]
@TheDeveloperGuy 

If you do not double-click the power button, the gesture data may be wrong

**Comment by GXiaoyang** [comment]
@TheDeveloperGuy 

You do not have to worry about the state of A, the first handle of the state may be wrong, so we let the user double click the power button

**Comment by GXiaoyang** [comment]
@TheDeveloperGuy 

I very much hope that you can like riftcat and trinus, can let NOLO go farther, thank you

**Comment by GXiaoyang** [comment]
@TheDeveloperGuy 

We hope that your software can access NOLO, so that more users experience your results

**Comment by TheDeveloperGuy** [comment]
@GXiaoyang I hope you can fix this issue, because otherwise I will not support Nolo in my software. I hope you can understand what I mean by 'quality' and that is the big difference between iVRy and Riftcat/Trinus. If I cannot bring Nolo up to the 'quality' I have in my product, then I will not bring the 'quality' of my product down for Nolo. 

Please let me know if you need any further help fixing this issue. I hope you can understand that there is more advantage to Nolo than there is to me for us to have a partnership.

**Comment by GXiaoyang** [comment]
@TheDeveloperGuy 

Please tear off the protective film under the base station

**Comment by GXiaoyang** [comment]
@TheDeveloperGuy 

Can you take a video for me? I have just tried the above steps and did not have an offset of 90 degrees, and we have sold a lot of equipment and no feedback on this question

**Comment by GXiaoyang** [comment]
@TheDeveloperGuy 

When you double-click the power button, the device yaw axis is 0

**Comment by GXiaoyang** [comment]
@TheDeveloperGuy 

I think we lack a good understanding, I am worried that you can not understand my thoughts, but also hope that we can think from each other's point of view

**Comment by TheDeveloperGuy** [comment]
@GXiaoyang There is no film under the base station. I will record a video so you can see the issue.

**Comment by TheDeveloperGuy** [comment]
@GXiaoyang I am worried that requiring the user to double-click a button on the controllers to get Nolo working correctly is not considered a problem.

**Comment by TheDeveloperGuy** [comment]
@GXiaoyang It's hard to record a video at the same time as moving the headset around. What happens is Nolo starts in state #B and then after about 5 seconds it switches to state #A, where it remains until the user double-clicks the power button. Once the user does this, it will remain in state #B until the headset tracker is unplugged.

**Comment by TheDeveloperGuy** [comment]
@GXiaoyang I have recorded a video and am uploading it. It will take about an hour, and I'll put a link here when that's ready. From the video, I can see that Nolo takes about 30 seconds to switch from state #B (correct) to state #A (incorrect).

**Comment by GXiaoyang** [comment]
thank you very much来自我的华为手机-------- 原始邮件 --------主题：Re: [NOLOVR/NOLO-Windows-SDK] Bug in recenter (double-clicking system) action (#8)发件人：TheDeveloperGuy 收件人：NOLOVR/NOLO-Windows-SDK 抄送：GXiaoyang <1050233151@qq.com>,Mention @GXiaoyang I have recorded a video and am uploading it. It will take about an hour, and I'll put a link here when that's ready. From the video, I can see that Nolo takes about 30 seconds to switch from state #B (correct) to state #A (incorrect).

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/NOLOVR/NOLO-Windows-SDK","title":"NOLOVR/NOLO-Windows-SDK","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/NOLOVR/NOLO-Windows-SDK"}},"updates":{"snippets":[{"icon":"PERSON","message":"@TheDeveloperGuy in #8: @GXiaoyang I have recorded a video and am uploading it. It will take about an hour, and I'll put a link here when that's ready. From the video, I can see that Nolo takes about 30 seconds to switch from state #B (correct) to state #A (incorrect). "}],"action":{"name":"View Issue","url":"https://github.com/NOLOVR/NOLO-Windows-SDK/issues/8#issuecomment-318359681"}}}

**Comment by TheDeveloperGuy** [comment]
@GXiaoyang In the end we all want the same thing, something that works, without bugs. 😉 

If you have a chance, please make some comments on issues #6 & #7 

Thank you

**Comment by Hettylool** [comment]
@TheDeveloperGuy  
Trigger button just have 1 or 0,this will not change in hardware.
 about velocity and acceleration values from Nolo IMU,we can't provide now,but can provide in the future.

**Comment by TheDeveloperGuy** [comment]
@Hettylool Thanks for the update. Issue #6 is important, as it's not possible to do controllers properly in SteamVR without this.

**Comment by TheDeveloperGuy** [comment]
@GXiaoyang You can find the video here:

http://www.mediator-software.com/iVRy/Nolo_Recenter_Bug.mov

You will probably need to download it first, I don't think the server is fast enough for streaming. 

0:00 - I start with 'fresh' Nolo (no buttons pressed)
0:36 - Nolo switches to 'bug' mode (no buttons pressed)
0:59 - I double-click 'recenter'

To get to Nolo 'fresh' state, I do:

- Exit Nolo software
- Unplug HMD tracker
- Turn on base station, plug in HMD tracker, turn on controllers
- Start Nolo software
- Do not press any controller buttons

**Comment by TheDeveloperGuy** [comment]
@GXiaoyang 0:00 & 0:59 are what I call state #B. 0:36 is what I call state #A.

**Comment by GXiaoyang** [comment]
@TheDeveloperGuy 
good morning

1: speed and acceleration we will provide later.
2: We provide handle-driven, inside the speed and acceleration are calculated by the SteamVR game to achieve throwing things
3: At present our trigger can only provide 0 and 1. will be improved later
4: NOLO users know and understand double-click the power button, the attitude calibration, which is our user requirements, if ivry access NOLO, must also require users to play the game before double-click the power button,
5: Our cooperation should be carried out step by step, the only way to quickly complete the work
6: For # 6 and # 7, we will be resolved in the future
7: if the cooperation is a car, # 6 and # 7 is a small stone, it does not affect the game's playability, but should not let it hinder our cooperation

**Comment by GXiaoyang** [comment]
@TheDeveloperGuy 
hi 
1: We will provide speed and acceleration in our SDK later,maybe in Q3. Before this comes true, you can caculate the speed and acceleration using position information, we can tell you the computing process and sample code.
2: At present NOLO's trigger button can only provide 0 and 1. will be improved in our next generation product.
3: NOLO get rotation data through IMU, the recenter function is necessary, I think that users can understand this. We will try our best to cancel this operation in our next generation product.

**Comment by TheDeveloperGuy** [comment]
@GXiaoyang Hi,

Thank you for your response.

What do you mean by "must also require users to play the game before double-click the power button"? What game is this?

"we can tell you the computing process and sample code" - Yes please, the code I am using presently causes 'jitter' so is unacceptable to me. I would like to try yours for comparison.

Did you watch the video I sent? It shows that the Nolo hardware/driver starts correctly then goes wrong after 30 seconds. Why is this?

Please also look at issue #9, if it is true, it is much more serious than any of these other issues.

**Comment by GXiaoyang** [comment]
@TheDeveloperGuy 

Have you experienced riftcat and trinus + NOLO to play the game? Have you seen Pimax + NOLO games? I hope you can try .

**Comment by TheDeveloperGuy** [comment]
@GXiaoyang 

What is "the game"?

What do you mean by "must also require users to play the game before double-click the power button"? What game is this?

Maybe I'm misunderstanding you. Do you mean "must require users to double-click power button before playing a game"?

I do not have Pimax, and I haven't tried Trinus or Riftcat, so please try to explain what you mean

**Comment by TheDeveloperGuy** [comment]
@GXiaoyang This communication is very frustrating! I post issues and wait 10 days for a response. I ask questions, you don't answer. You offer me code, I accept, but you don't give. I send you bug reports, but you ignore. I am very close to giving up with Nolo. I have very limited time and this is taking too much of it.

**Comment by GXiaoyang** [comment]
@TheDeveloperGuy 
hi
My English is not good, by Google translation, yes you understand the wrong, but also I expressed the wrong

**Comment by GXiaoyang** [comment]
@TheDeveloperGuy 

I am sorry for the two weeks on a business trip

**Comment by GXiaoyang** [comment]
@TheDeveloperGuy 
I am in China, have a certain time difference, please understand

**Comment by GXiaoyang** [comment]
@TheDeveloperGuy 

Now I want to work with you

**Comment by TheDeveloperGuy** [comment]
@GXiaoyang I understand. This is the last day I will work on Nolo until September. If we don't resolve the issues I have today, then we will wait until September. Your users are crying to me because Trinus and Riftcat are such bad quality. I want to add Nolo support, but I will not do it if it reduces the quality of my product. If you cannot address the issues I raise, then I cannot work with Nolo. 

- Please provide the code for velocity/acceleration so I can test it
- Please answer #9 
- Please provide an explanation for what is happening in the video I sent you

**Comment by GXiaoyang** [comment]
@TheDeveloperGuy 
My code
https://github.com/NOLOVR/NOLO-Others/tree/master/MyDriverSource

**Comment by GXiaoyang** [comment]
@TheDeveloperGuy 
1. I will modify charperone_info.vrchap to make Room Setup, because Chinese users can’t use the Room Setup function in SteamVR.

**Comment by TheDeveloperGuy** [comment]
@GXiaoyang Thank you for the code. 

Unfortunately, whatever you are doing with the chaperone file is **wrong**. It **destroys** the room setup for all headsets (even ones that do not use Nolo) and the user must do again. This is something that **must** be fixed. I think we have a difference in understanding what is acceptable to users. It is **not acceptable** that they must reenter settings each time because of bugs in Nolo. 

I'm sorry, but it looks like the bugs in Nolo will stop me from supporting it at this time. Maybe it's better I look again in September and see if you have fixed some issues by then. I **can not** and **will not** make my product bad quality because of bugs in Nolo. It makes me **very unhappy** to try to work with software that is broken. If you want to fix it, let me know when you have fixed so I can try again.

**Comment by GXiaoyang** [comment]
@TheDeveloperGuy 
Hello, for fresh users the Steam VR room setting is too complex, so I modified the chaperone_info.vrchap to simple the room setting process. I have seen your video, now I will tell you the reason, when you power on NOLO's headset maker, the IMU in it need some time to initialize. After initialization, the ration will be stable.

**Comment by TheDeveloperGuy** [comment]
@GXiaoyang You do not have permission to modify the chaperone info file, whatever your reasons are.

**Comment by TheDeveloperGuy** [comment]
@GXiaoyang If you can provide me with a version of the Nolo software that does not modify **private** SteamVR config files, today, we can continue. Otherwise we are finished for now. Thank you.

**Comment by GXiaoyang** [comment]
@TheDeveloperGuy 
I can provide you a new SDK, we do not need NOLO PC software if we directly read NOLO data through USB and I won't modify configuration files of Steam VR.

**Comment by TheDeveloperGuy** [comment]
@GXiaoyang Perfect. I do not want to use NOLO PC software. It is causing too many problems.

**Comment by GXiaoyang** [comment]
https://github.com/NOLOVR/NOLO-Others/tree/master/NOLO_NewSDK

**Comment by GXiaoyang** [comment]
@TheDeveloperGuy 
hi
Ok, new SDK doesn't need NOLO PC software, I will do my best to satisfy your requirement if you need.
I'm really sorry for my poor English, I almost lost such a brilliant partner. Thanks for your patience.

**Comment by TheDeveloperGuy** [comment]
@GXiaoyang I appreciate you trying to make it work for all of us. I need to understand what I'm supposed to be doing with this SDK. Also I need 32 bit and 64 bit versions of all DLL and LIB files.

**Comment by GXiaoyang** [comment]
@TheDeveloperGuy 
I will provide you as soon as possible to meet your requirements

**Comment by TheDeveloperGuy** [comment]
@GXiaoyang So how do I use this SDK?

**Comment by TheDeveloperGuy** [comment]
@GXiaoyang Thanks, it seems this SDK is missing:

noloDataNotify_FuncCallBack(noloData_FuncCallBackNotify fun)

I can work around that for now, but I need to understand what this library is. Is it included with the standard Nolo installation? If not, will it be included? Do I even need the standard Nolo installation if I use this SDK?

**Comment by TheDeveloperGuy** [comment]
@GXiaoyang This library fails when calling open_Nolo_ZeroMQ()

**Comment by TheDeveloperGuy** [comment]
@GXiaoyang This SDK does not work at all. It fails when I call open_Nolo_ZeroMQ(). If I don't call that, then all the other functions fail. What is this? Did you ever test it?

**Comment by TheDeveloperGuy** [comment]
@GXiaoyang I think it is too early to try to support Nolo. I will wait some months and look again when your software is (hopefully) improved. I have lots of other work to do. I cannot waste more time with this. What is the point of giving me a broken SDK with no instructions?

**Comment by TheDeveloperGuy** [comment]
Thank you for your time, I hope you can understand the concept of "quality of experience" and try to achieve that with the Nolo software. Your company will succeed or fail in the western market depending on the "quality of experience" that it can deliver. At the moment, the quality is too low for us to have a partnership. I hope you can improve it.

**Comment by TheDeveloperGuy** [comment]
良好的品质经验 is important

**Comment by GXiaoyang** [comment]
@TheDeveloperGuy 
We are sorry for the inconvenience.Currently, we do not have the English instruction. It will take some time to translate it into English.Please wait a few days. Thanks for your patience and support

**Comment by TheDeveloperGuy** [comment]
@GXiaoyang The "new" SDK **does not work** at all, I do not need instructions. I am not working on this after today. What we can achieve today will be what we can achieve until September.

**Comment by TheDeveloperGuy** [comment]
@GXiaoyang I tried the updated "new" SDK that you've now removed from Github. It doesn't work at all. Maybe there's some secret to using it that you never told me? If I try to use it like the standard SDK it doesn't work at all, it fails at open_Nolo_ZeroMQ().

**Comment by TheDeveloperGuy** [comment]
@GXiaoyang I had to release my driver in BETA state as I'm not able to work on this any more at present. You can find it here if you'd like to test it or whatever:

http://forums.nolovr.com/discussion/436/beta-nolovr-compatible-driver-for-ivry-available

**Comment by GXiaoyang** [comment]
@TheDeveloperGuy 
hi
 it takes me one week to sort out SDK. I hope this new SDK will not disappoint you. Thanks for your patience!

**Comment by TheDeveloperGuy** [comment]
@GXiaoyang  Please make sure you test it properly. The previous "new SDK" did not work at all. Thank you.

**Comment by GXiaoyang** [comment]
@TheDeveloperGuy 
hi
^_^
It was a little hurry before. I have tested the new SDK this time. Thanks for your support, and I am very happy to communicate and cooperate with you again!

**Comment by TheDeveloperGuy** [comment]
@GXiaoyang  Ok, I will try to test this some time soon. I won't have a chance to do any more development with NoloVR until September. If I need to change some of my code to use this SDK, please explain what I need to change so I don't waste time. Thank you.

**Comment by TheDeveloperGuy** [comment]
@GXiaoyang  Thank you for the new SDK. Much better! 😄 👍 

I have released a new driver based on this SDK, which works correctly with no NoloVR software installed on the PC.

**Comment by GXiaoyang** [comment]
@TheDeveloperGuy 
👍👍
